spring:

  datasource:
    url: jdbc:mysql://81.70.89.185/cms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zxcvbnm,./0

  servlet:
    multipart:
      enabled: true
      location: uploads

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG


